### ISSUE TITLE
Unable to build - TypeError: Cannot read property 'stat' of undefined

### ISSUE THREAD

**Issue by robinhundt** [yewstack/yew-wasm-pack-template#19]
After cloning the repo, installing the dependencies with
```
yarn install
```
all the commands provided in the `pachakge.json` result in the following error:
```
➜  yew-wasm-pack-template git:(master) yarn run build
yarn run v1.22.4
$ webpack --mode production
🧐  Checking for wasm-pack...

✅  wasm-pack is installed. 

ℹ️  Compiling your crate in release mode...

TypeError: Cannot read property 'stat' of undefined
    at WasmPackPlugin._compile (/home/robin/code/yew-wasm-pack-template/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:130:24)
    at _checkWasmPack.then (/home/robin/code/yew-wasm-pack-template/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:66:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'd be very happy if someone had a clue why i can't compile the template.

**Comment by robinhundt** [comment]
Mhh, it seems my node installation was somehow broken (or too old?). Installing the newest version fixed the error.

**Comment by cesars-gh** [comment]
Thanks @robinhundt that solved my issue. I forgot to switch to a newer Node version in my local dev environment
